// <auto-generated />
using BatConnect.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BattConnect.Data.Migrations
{
    [DbContext(typeof(BattConnectDbContext))]
    [Migration("20211215185217_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("BattConnect.Core.Models.ChargingCompany", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("ChargingCompanies");
                });

            modelBuilder.Entity("BattConnect.Core.Models.SocketType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("ChargingCompanyId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ChargingCompanyId");

                    b.ToTable("SocketTypes");
                });

            modelBuilder.Entity("BattConnect.Core.Models.SocketType", b =>
                {
                    b.HasOne("BattConnect.Core.Models.ChargingCompany", "ChargingCompany")
                        .WithMany("SocketTypes")
                        .HasForeignKey("ChargingCompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChargingCompany");
                });

            modelBuilder.Entity("BattConnect.Core.Models.ChargingCompany", b =>
                {
                    b.Navigation("SocketTypes");
                });
#pragma warning restore 612, 618
        }
    }
}
